lib/beacon_ball_web/router.ex
defmodule BeaconBallWeb.Router do
  use BeaconBallWeb, :router

  for p <- [:browser_public, :browser_protected, :admin_only, :admin_or_self_only] do
    pipeline :"#{p}" do
      plug :accepts, ["html"]
      plug :fetch_session
      plug :fetch_live_flash
      plug :put_root_layout, {BeaconBallWeb.LayoutView, :root}
      plug :protect_from_forgery
      plug :put_secure_browser_headers
      plug BeaconBallWeb.Plugs.Authentication

      if p != :browser_public do
        plug BeaconBallWeb.Plugs.AuthOrRedirectToLogin
      end

      case p do
        :admin_only ->
          plug BeaconBallWeb.Plugs.AdminOnly

        :admin_or_self_only ->
          plug BeaconBallWeb.Plugs.AdminOrSelfOnly

        _ ->
          nil
      end
    end
  end

  scope "/login", BeaconBallWeb do
    pipe_through :browser_public

    live "/", LoginLive.Index, :index
  end

  scope "/players", BeaconBallWeb do
    pipe_through :admin_only
    live "/new", PlayerLive.Index, :new
  end

  scope "/players", BeaconBallWeb do
    pipe_through :admin_or_self_only

    live "/:id/edit", PlayerLive.Index, :edit
    live "/:id/show/edit", PlayerLive.Show, :edit
  end

  scope "/runs", BeaconBallWeb do
    pipe_through :admin_only

    live "/new", RunLive.Index, :new
    live "/:id/edit", RunLive.Index, :edit
    live "/:id/show/edit", RunLive.Show, :edit
  end

  scope "/", BeaconBallWeb do
    pipe_through :browser_protected

    live "/players", PlayerLive.Index, :index
    live "/players/:id", PlayerLive.Show, :show

    live "/runs", RunLive.Index, :index
    live "/runs/:id", RunLive.Show, :show

    get "/", Plugs.Redirect, to: "/runs"
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser_public

      live_dashboard "/dashboard", metrics: BeaconBallWeb.Telemetry
    end
  end
end

lib/beacon_ball_web/views/layout_view.ex
defmodule BeaconBallWeb.LayoutView do
  use BeaconBallWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/beacon_ball_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/beacon_ball_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/beacon_ball_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "BeaconBall", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <%= if Phoenix.Controller.current_path(@conn) != "/login" do %>
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
      <nav>
        <%= live_redirect "Runs", to: Routes.run_index_path(@conn, :index) %>
        |
        <%= live_redirect "Players", to: Routes.player_index_path(@conn, :index) %>
      </nav>
      <span><%= link "Log out", to: "/", phx_click: "logout", data: [confirm: "Are you sure?"] %></span>
    </div>
  <% end %>
  <body>
    <%= @inner_content %>
  </body>
</html>